import dbus

proxy = dbus.SystemBus().get_object('apps.nano77.gdm3setup','/apps/nano77/gdm3setup')

SetShellTheme = proxy.get_dbus_method('SetShellTheme','apps.nano77.gdm3setup')
GetShellTheme = proxy.get_dbus_method('GetShellTheme','apps.nano77.gdm3setup')
SetGtkTheme = proxy.get_dbus_method('SetGtkTheme','apps.nano77.gdm3setup')
GetGtkTheme = proxy.get_dbus_method('GetGtkTheme','apps.nano77.gdm3setup')
SetIconTheme = proxy.get_dbus_method('SetIconTheme','apps.nano77.gdm3setup')
GetIconTheme = proxy.get_dbus_method('GetIconTheme','apps.nano77.gdm3setup')
SetFont = proxy.get_dbus_method('SetFont','apps.nano77.gdm3setup')
GetFont = proxy.get_dbus_method('GetFont','apps.nano77.gdm3setup')
SetCursorTheme = proxy.get_dbus_method('SetCursorTheme','apps.nano77.gdm3setup')
GetCursorTheme = proxy.get_dbus_method('GetCursorTheme','apps.nano77.gdm3setup')
SetLogoIcon = proxy.get_dbus_method('SetLogoIcon','apps.nano77.gdm3setup')
GetLogoIcon = proxy.get_dbus_method('GetLogoIcon','apps.nano77.gdm3setup')
SetFallbackLogo = proxy.get_dbus_method('SetFallbackLogo','apps.nano77.gdm3setup')
GetFallbackLogo = proxy.get_dbus_method('GetFallbackLogo','apps.nano77.gdm3setup')
SetShellLogo = proxy.get_dbus_method('SetShellLogo','apps.nano77.gdm3setup')
GetShellLogo = proxy.get_dbus_method('GetShellLogo','apps.nano77.gdm3setup')
SetWallpaper = proxy.get_dbus_method('SetWallpaper','apps.nano77.gdm3setup')
GetWallpaper = proxy.get_dbus_method('GetWallpaper','apps.nano77.gdm3setup')
SetUserListVisibility = proxy.get_dbus_method('SetUserListVisibility','apps.nano77.gdm3setup')
GetUserListVisibility = proxy.get_dbus_method('GetUserListVisibility','apps.nano77.gdm3setup')
SetRestartMenuVisibility = proxy.get_dbus_method('SetRestartMenuVisibility','apps.nano77.gdm3setup')
GetRestartMenuVisibility = proxy.get_dbus_method('GetRestartMenuVisibility','apps.nano77.gdm3setup')
SetBannerVisibility = proxy.get_dbus_method('SetBannerVisibility','apps.nano77.gdm3setup')
GetBannerVisibility = proxy.get_dbus_method('GetBannerVisibility','apps.nano77.gdm3setup')
SetBannerText = proxy.get_dbus_method('SetBannerText','apps.nano77.gdm3setup')
GetBannerText = proxy.get_dbus_method('GetBannerText','apps.nano77.gdm3setup')
SetClockDateVisibility = proxy.get_dbus_method('SetClockDateVisibility','apps.nano77.gdm3setup')
GetClockDateVisibility = proxy.get_dbus_method('GetClockDateVisibility','apps.nano77.gdm3setup')
SetClockSecondsVisibility = proxy.get_dbus_method('SetClockSecondsVisibility','apps.nano77.gdm3setup')
GetClockSecondsVisibility = proxy.get_dbus_method('GetClockSecondsVisibility','apps.nano77.gdm3setup')
SetFingerprintAuthentication = proxy.get_dbus_method('SetFingerprintAuthentication','apps.nano77.gdm3setup')
GetFingerprintAuthentication = proxy.get_dbus_method('GetFingerprintAuthentication','apps.nano77.gdm3setup')
SetPasswordAuthentication = proxy.get_dbus_method('SetPasswordAuthentication','apps.nano77.gdm3setup')
GetPasswordAuthentication = proxy.get_dbus_method('GetPasswordAuthentication','apps.nano77.gdm3setup')
SetSmartcardAuthentication = proxy.get_dbus_method('SetSmartcardAuthentication','apps.nano77.gdm3setup')
GetSmartcardAuthentication = proxy.get_dbus_method('GetSmartcardAuthentication','apps.nano77.gdm3setup')
SetAllowedFailures = proxy.get_dbus_method('SetAllowedFailures', 'apps.nano77.gdm3setup')
GetAllowedFailures = proxy.get_dbus_method('GetAllowedFailures', 'apps.nano77.gdm3setup')
StopDaemon = proxy.get_dbus_method('StopDaemon', 'apps.nano77.gdm3setup')

SetAutoLoginState = proxy.get_dbus_method('SetAutoLoginState', 'apps.nano77.gdm3setup')
GetAutoLoginState = proxy.get_dbus_method('GetAutoLoginState', 'apps.nano77.gdm3setup')
SetAutoLoginUserName = proxy.get_dbus_method('SetAutoLoginUserName', 'apps.nano77.gdm3setup')
GetAutoLoginUserName = proxy.get_dbus_method('GetAutoLoginUserName', 'apps.nano77.gdm3setup')
SetAutoLoginTimed = proxy.get_dbus_method('SetAutoLoginTimed', 'apps.nano77.gdm3setup')
GetAutoLoginTimed = proxy.get_dbus_method('GetAutoLoginTimed', 'apps.nano77.gdm3setup')
SetAutoLoginTime = proxy.get_dbus_method('SetAutoLoginTime', 'apps.nano77.gdm3setup')
GetAutoLoginTime = proxy.get_dbus_method('GetAutoLoginTime', 'apps.nano77.gdm3setup')

